version: "3.9"

services:
  app:
    build: .
    container_name: anomaly_app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=anomaly_db

  db:
    image: postgres:14
    container_name: anomaly_db
    restart: always
    environment:
      POSTGRES_DB: anomaly_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
